### ISSUE TITLE
Add more favicons

### ISSUE THREAD

**Issue by SirZach** [SirZach/foosball#107]
Before the new favicon was put in, if I added to home screen on my Android phone it would use the favicon as the app symbol. I think this was because you created all the different kinds of favicons. Can you do that again with the new icon?

**Comment by Createor** [comment]
Do you happen to remember where I did that?

**Comment by SirZach** [comment]
https://github.com/SirZach/foosball/commit/4c03bd1efbc8214720549cd65c227bff00a8bf10

**Comment by Createor** [comment]
I meant what tool I used ;) I'll check my history

**Comment by SirZach** [comment]
Oh I have no idea. It was pure magic when you did it

**Comment by SirZach** [comment]
closed by #108
