### ISSUE TITLE
I'm better than Jordan, just saying

### ISSUE THREAD

**Issue by imabutthole** [SirZach/foosball#47]
![image](https://cloud.githubusercontent.com/assets/16342488/11882832/e630275e-a4dc-11e5-9218-e05d29864b0e.png)

**Comment by Createor** [comment]
Moving to 3 decimal places to reduce the chance of this.

**Comment by Createor** [comment]
@SirZach Should sorting be based on just the float math, and we then have scorekeeper keep track of the display ratio as an additional variable generated at the same time?

**Comment by SirZach** [comment]
@iamabutthole I love that you signed up for github. That's awesome. As for @createor, not sure what you mean by float math... Or the rest of your comment

**Comment by SirZach** [comment]
resolved.
