### ISSUE TITLE
1.0

### ISSUE THREAD

**Issue by SirZach** [SirZach/foosball#65]

**Comment by SirZach** [comment]
![screen shot 2016-04-29 at 12 45 57 am](https://cloud.githubusercontent.com/assets/1113484/14908635/9873ceb0-0da7-11e6-8ff7-d6b251bdbf80.png) @Createor making progress!

**Comment by SirZach** [comment]
![screen shot 2016-05-07 at 12 30 53 am](https://cloud.githubusercontent.com/assets/1113484/15090179/fffde1b2-13ea-11e6-8eb8-108998e2857e.png)

**Comment by SirZach** [comment]
![screen shot 2016-05-10 at 12 24 54 am](https://cloud.githubusercontent.com/assets/1113484/15135566/afc90a84-1645-11e6-9977-b17ebd053c7b.png)
@Createor making progress on the new teams page!

**Comment by Createor** [comment]
For the games page, should there be some visual indication of games you lost?

**Comment by SirZach** [comment]
just you wait

**Comment by SirZach** [comment]
comment to test webhook

**Comment by SirZach** [comment]
![screen shot 2016-05-11 at 11 54 58 pm](https://cloud.githubusercontent.com/assets/1113484/15203660/d3abcdee-17d3-11e6-907d-e2ca5f74971d.png) tabs to act as filters

**Comment by SirZach** [comment]
![screen shot 2016-05-18 at 1 40 25 am](https://cloud.githubusercontent.com/assets/1113484/15348507/8522acae-1c99-11e6-964c-b801dc10a4ba.png)
@Createor can you try logging in and linking your user to see how the experience is?

**Comment by Createor** [comment]
Looks great! Got hooked right up!

**Comment by Createor** [comment]
New layout items left to do:
- [ ] After login, user should continue on to requested destination
- [ ] Profile card links
- [ ] App Icon
- [ ] Clicking on profile icon link to profile page
- [ ] Footer text spacing
- [ ] Profile card image replaced with performance graph
- [ ] Game button has to function
- [ ] About page content
- [ ] League rules page content
- [ ] Make player names clickable and show on hover
- [ ] Replace 'Foosers' with 'Players'
- [ ] Home page
  - [ ] Only highlight logged in player in game list 
  - [ ] Games section title
  - [ ] Add game quick card
  - [ ] Dasherize team names
- [ ] Teams Page
  - [ ] Line up the columns
  - [ ] Sorting
  - [ ] My teams tab
  - [ ] Highlight logged in player in All Teams list
- [ ] Foosers page
  - [ ] Sorting
  - [ ] Remove the 'ALL FOOSERS' and 'ME' tabs
- [ ] Profile page
  - [ ] Exist

**Comment by Createor** [comment]
Items left after layout:
- [ ] Add email/password auth
- [ ] Complete ember-paper upgrade
- [ ] Complete validation and access rules
- [ ] Fix scrollbars

**Comment by SirZach** [comment]
@TheConnMan adding you to the issue so you can how much or how little progress is being made

**Comment by SirZach** [comment]
<img width="906" alt="screen shot 2016-06-08 at 10 33 18 am" src="https://cloud.githubusercontent.com/assets/1113484/15897933/56c03cec-2d64-11e6-891b-2a184549d05f.png">
sorting

**Comment by SirZach** [comment]
![screen shot 2016-06-08 at 11 45 56 pm](https://cloud.githubusercontent.com/assets/1113484/15918278/3219cb96-2dd3-11e6-9f56-e8b6828a49c7.png)
team sorting

**Comment by SirZach** [comment]
![screen shot 2016-06-09 at 1 12 45 am](https://cloud.githubusercontent.com/assets/1113484/15919445/68769c26-2ddf-11e6-8d47-c775924b0fe2.png)
![screen shot 2016-06-09 at 1 13 00 am](https://cloud.githubusercontent.com/assets/1113484/15919446/6bc523e8-2ddf-11e6-8c13-3368fdcbe278.png)
![screen shot 2016-06-09 at 1 13 19 am](https://cloud.githubusercontent.com/assets/1113484/15919449/6eccc258-2ddf-11e6-974c-babb0bf157e8.png)
profile page

**Comment by SirZach** [comment]
![screen shot 2016-08-03 at 11 40 48 pm](https://cloud.githubusercontent.com/assets/1113484/17389603/c5964cc4-59d3-11e6-8386-42238c8bb8c6.png)
player stats as profile image

**Comment by SirZach** [comment]
![screen shot 2016-08-07 at 11 59 14 pm](https://cloud.githubusercontent.com/assets/1113484/17468995/087551aa-5cfb-11e6-924e-fa84a83edd84.png)
![screen shot 2016-08-07 at 11 59 32 pm](https://cloud.githubusercontent.com/assets/1113484/17468997/0b7b5282-5cfb-11e6-87d1-9a69b8c78911.png)

new game

**Comment by SirZach** [comment]
closing this finally!
