### ISSUE TITLE
Prolong the auth timeout

### ISSUE THREAD

**Issue by SirZach** [SirZach/foosball#86]
Every 24 hours you get logged out. This isn't ideal and sucks to make people log in all the time. The old firebase console had a way of extending how long the auth would last.

**Comment by Createor** [comment]
https://groups.google.com/forum/#!msg/firebase-talk/4Q2qC1jFPjk/3DgbdHIJFwAJ

Can't be done :disappointed:

**Comment by SirZach** [comment]
dang that sucks
