### ISSUE TITLE
filter out retired users from the choose-fooser page

### ISSUE THREAD

**Issue by SirZach** [SirZach/foosball#91]
no need to show retired users that just get in the way

**Comment by Createor** [comment]
I added a "status" field to the user data for this. Initially I only have active and retired, but we can add statuses as we see fit.

**Comment by SirZach** [comment]
i was thinking of having something like `retired: true` which makes `if` statements easier

**Comment by Createor** [comment]
We could do it that way, my thinking here was we can extend it to filtering out users who do not have enough games based on the status field rather than by counting the games.

**Comment by SirZach** [comment]
sure, we could have another field `active: true`
